//input all the members here, doesn't have to be alphabetically sorted
export const members = new Set([
  //input member names below 'name',
  'exsample1',
  'aphofis',
  'bee',
  'chiefy',
  'dabes',
  'desneign',
  'donald',
  'h311born',
  'haru',
  'hazewise',
  'ievylo',
  'jiangjun',
  'kazin',
  'lockon',
  'mimi',
  'minajype',
  'nautilus',
  'omgilost',
  'pz',
  'rudi',
  'shadow',
  'shift',
  'slash',
  'spleen',
  'teddy',
  'titanicd',
  'troy',
  'val',
  'vanilabr',
  'yarly',
  'zachary',
]);
